from random import randint

# create list of 100 random numbers from 0 to 1000
rand_nums = [randint(0, 1000) for _ in range(100)]
"""
Generating random numbers using 'randint' function from builtin 'random' module.
Assuming both 0 and 1000 should be included.
"""


def sort_list(arr):
    """Sorts integers in a list."""
    n = len(arr)
    for i in range(n - 1):
        for j in range(i + 1, n):
            if arr[i] > arr[j]:
                arr[i], arr[j] = arr[j], arr[i]
"""
Algorithm works like this:
first pointer <i> goes from first element to last - 1;
second pointer <j> goes from first pointer + 1 to last element;
if element on first pointer greater than element on second, swap elements.
"""

# sort list from min to max (without using sort())
sorted_rand_nums = []
"""New list for sorted values."""
while rand_nums:
    """While we have numbers in unsorted list."""
    min_num = min(rand_nums)
    """Search for minimal number in unsorted list."""
    for _ in range(rand_nums.count(min_num)):
        """Doing operations for each of that minimum numbers."""
        sorted_rand_nums.append(min_num)
        """Appending current minimal number to the new list."""
        rand_nums.remove(min_num)
        """Removing current minimal number from unsorted list."""

# calculate average for even and odd numbers
even_nums, odd_nums = [], []
"""Creating two new lists for even/odd numbers."""
for num in sorted_rand_nums:
    """Looping through all numbers in sorted list."""
    if num % 2 == 0:
        """If remainder of division by 2 of current number eq to 0."""
        even_nums.append(num)
        """Appending current number to even numbers list."""
    else:
        """In other case number is odd."""
        odd_nums.append(num)
        """Appending current number to odd numbers list."""
"""
Note that if we've got 0 generated by randint - it will be passed to even numbers.
Not sure if it is right way. In real task I'll go and clarify this nuance with task giver.
"""

even_nums_avg = sum(even_nums) / len(even_nums)
"""Calculating average of even numbers in a list by diving sum of them by their overall count."""
odd_nums_avg = sum(odd_nums) / len(odd_nums)
"""Calculating average of odd numbers in a list by diving sum of them by their overall count."""

# print both average result in console
print(f"Average of even numbers: {even_nums_avg}")
print(f"Average of odd numbers: {odd_nums_avg}")

print(f"{rand_nums=}")
print(f"{sorted_rand_nums=}")
print(f"{even_nums=}")
print(f"{odd_nums=}")
